In [2]:
import numpy as np

In [6]:
#1.Use numpy to generate array of 25 random numbers sampled from a standard normal distribution

array = np.random.randn(25)
array

array([-0.94790364, -0.24299807, -1.28768009, -1.97054733,  0.00541668,
       -0.91617317,  1.05292632, -1.31534444,  0.79795901,  0.12108801,
        0.09717511,  0.5679084 ,  0.12646635, -0.79437088,  0.27231853,
       -1.19255824,  1.89984   ,  0.37842785,  1.29814132, -0.58668496,
        0.29550575,  0.29522223,  0.75382583,  0.36722844,  1.42255722])

In [16]:
#2.Create a random vector of size 30 and find the mean value.
np.random.seed(8)
arr=np.random.randint(0,100,30)
print(arr)
print(np.mean(arr,axis=0))

[67 84  5 90  8 83 63 48 85 60 49 74 27 13  9 61 15 93 98 59 18 14 93 56
  9 51 68 53 53 71]
52.56666666666667


In [17]:
#3.Insert 1 to 100 numbers in a numpy array and reshape it to 10*10 matrix.
arr=np.random.randint(1,100,(10,10))
arr

array([[60, 43, 27, 67, 10, 82, 16, 93, 92, 64],
       [87, 32, 21, 46, 22, 73, 93, 29, 96, 48],
       [11, 65,  8, 46,  3, 39, 72, 96, 37, 90],
       [61, 92, 69, 38, 67, 83, 39, 55, 87, 40],
       [47,  7, 96, 33, 74, 99,  8, 10, 99, 43],
       [20, 60, 49, 10, 17, 79, 56, 56, 21, 99],
       [88, 99, 25,  7, 29,  6, 67, 20, 76, 12],
       [47, 93, 73, 56, 90, 15, 40, 16, 20, 59],
       [44, 16, 29, 33, 42, 17, 75, 34, 67, 71],
       [63,  8, 84,  9, 35, 42, 46, 23, 77, 93]])

In [10]:
#4.Create a 10x10 array with random values and find the minimum and maximum values.
arr=np.random.randint(1,100,(10,10))
print(np.min(arr))
print(np.max(arr))

2
99


In [11]:
#5.Find Dot product of two arrays
f = np.array([1,2])
g = np.array([4,5])
print(np.dot(f,g))

14


In [13]:
#6.Concatenate following arrays along axis=0
x=np.array([[1,2],[3,4]])
y=np.array([[5,6]])
comb = np.concatenate((x,y), axis = 0)
print(comb)

[[1 2]
 [3 4]
 [5 6]]


In [14]:
#7.How to get the common items between two python numpy arrays?

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
common = np.intersect1d(a,b)
print(common)

[2 4]


In [15]:
#8.Sort the numpy array:

arr = np.array([10,5,8,4,7,2,3,1])
print(np.sort(arr))

[ 1  2  3  4  5  7  8 10]
